name: exhale_pred
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - monai=1.5.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - pandas
  - nibabel
  - jupyter
  - matplotlib
  - wandb
  - tqdm
  - pip
  - pip:
    - piqa==1.3.2
    - torchmetrics==1.8.2
    - einops
    - gitpython