name: exhale_pred
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - monai
  - scikit-image
  - scikit-learn
  - scipy
  - pandas
  - nibabel
  - jupyter
  - matplotlib
  - wandb
  - tqdm
  - pip
  - pip:
    - piqa==1.3.2
    - torchmetrics==1.8.2
    - einops
    - gitpython